
---
title: "P8105 Homework 6: NYC Restaurant Shiny"
author: "Mengqi Zhu (mz2662) & Pengfei Jiang (pj2325)"
date: "2017/11/15"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(plotly)
library(shiny)
```

```{r}
#read and clean data
nyc_inspections <- 
  read_csv("DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", 
                           col_types = cols(building = col_character()),
                           na = c("NA", "N/A")) %>%
  clean_names() %>%
  filter(grade %in% c("A", "B", "C"),
         boro != "Missing") %>% 
  mutate(inspection_num = row_number(),
         boro = str_to_title(boro)) %>% 
  select(inspection_num, boro, grade, score, critical_flag, cuisine_description)
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r, siderbar}
boros <- 
  nyc_inspections %>% distinct(boro) %>% pull()

cuisines <- 
  nyc_inspections %>% distinct(cuisine_description) %>% pull()

#radioButtons widget
radioButtons("boro_choice", label = h3("Select boro"),
             choices = boros, selected = "Manhattan")

#selectInput widget
selectInput("select_critical_flag", label = h3("Select critical flag"), 
    choices = list("Critical" = "Critical", "Not Critical" = "Not Critical", "Not Applicable" = "Not Applicable"), 
    selected = "Critical")

```


Row
-----------------------------------------------------------------------

### Grade A Percentage vs Average Score ScatterPlot

```{r, chartA}
renderPlotly({
  nyc_inspections %>%
  group_by(boro, cuisine_description, critical_flag) %>%
  summarise(aver_score = mean(score),
            num_inspections = n(),
            A_num = sum(grade == "A"),
            A_percent = sum(grade == "A")/n(),
            critaical_percent = sum(grade == "A")/n()) %>%
    filter(boro == input$boro_choice,
         critical_flag == input$select_critical_flag) %>%
  mutate(text_label = str_c("Boro: ", boro, '\nCuisine: ', cuisine_description, 
                            '\nnumber of inspection:', num_inspections, '\nnumber of A:', A_num,
                            '\n A%:', paste(round(A_percent*100,digits = 2),"%",sep = "")), 
                            '\n critical%:', paste(round(critaical_percent*100,digits = 2),"%",sep = "")) %>%
  plot_ly(x = ~A_percent, y = ~aver_score, type = "scatter", mode = "markers",   
          alpha = 0.7, color = ~boro, text = ~text_label)
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Boxplot of Scores

```{r, chartB}
renderPlotly({
cuisine_boxplot <-
  nyc_inspections %>%
  filter(boro == input$boro_choice) %>%
  group_by(cuisine_description) %>%
  summarise(num_inspections = n()) %>%
  top_n(5, num_inspections) %>%
  pull(cuisine_description)
nyc_inspections %>%
  filter(boro == input$boro_choice,
         cuisine_description %in% cuisine_boxplot,
         critical_flag == input$select_critical_flag) %>%
  plot_ly(y = ~score, color = ~cuisine_description, type = "box", colors = "Set2")
})
```

### Bar-plot for Average Scores by Cuisine

```{r, chartC}
renderPlotly({
  nyc_inspections %>%
  group_by(boro, cuisine_description, critical_flag) %>%
  summarise(aver_score = mean(score),
            num_inspections = n(),
            A_num = sum(grade == "A"),
            A_percent = sum(grade == "A")/n(),
            critaical_percent = sum(grade == "A")/n()) %>%
  mutate(text_label = str_c("Boro: ", boro, '\nCuisine: ', cuisine_description, 
                            '\nnumber of inspection:', num_inspections, '\nnumber of A:', A_num,
                            '\n A%:', paste(round(A_percent*100, digits = 2),"%",sep = "")), 
                            '\n critical%:', paste(round(critaical_percent*100, digits = 2),"%",sep = "")) %>%
  filter(boro == input$boro_choice,
         critical_flag == input$select_critical_flag) %>%
  plot_ly(x = ~cuisine_description, y = ~aver_score, color = ~cuisine_description, type = "bar", text = ~text_label) %>%
  layout(showlegend = FALSE)
})
```